%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/maxle/Desktop/Link to CFD_FALL_17/codingHW1/FTCS_explicit.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/09/27 23:08:29

%% Initialize variables.
filename = '/home/maxle/Desktop/Link to CFD_FALL_17/codingHW1/FTCS_explicit005.txt';
delimiter = '\t';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
FTCSexplicit = [dataArray{1:end-1}];

%%Transpose

A = FTCSexplicit.';

%%Plotting

plot(A(:,1),A(:,2),'-b');
hold on
box on
grid on
plot(A(:,3),A(:,4),'-xr');
plot(A(:,5),A(:,6),'-sk');
plot(A(:,7),A(:,8),'-vg');
xlabel('X [ft]')
ylabel('T [degree F]')
title('FTCS explicit scheme,dt=0.05 hr','interpreter','latex','fontsize',11);
legend('location','bestoutside','t = 0.1 hr','t = 0.2 hr', 't = 0.3 hr', 't = 0.4 hr');
k = waitforbuttonpress
saveas(gcf,'FTCS_explicit005.jpg')



%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;
