%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/maxle/Desktop/data.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/09/13 17:39:55

%% Initialize variables.
filename = '/home/maxle/Desktop/data.txt';
delimiter = '\t';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
X = dataArray{:, 1};
U = dataArray{:, 2};

%%Plotting
plot(X,U);
grid on
box on
k = waitforbuttonpress;



%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;